environment:
  matrix:
    - nodejs_version: '4'
    - nodejs_version: '6'
    - nodejs_version: '8'
    - nodejs_version: '9'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm cache clear --force
  - npm i npm@latest -g
  - set PATH=%APPDATA%\npm;%PATH%
  - set CONTINUOUS_INTEGRATION=true
  - set CI=true
  - npm config set progress=false
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
matrix:
  fast_finish: true
build: off
test_script:
  - node --version
  - npm --version
  - npm test
